apiVersion: v1
kind: Service
metadata:
    name: posts-srv-np
spec:
    type: NodePort # the type of Service, ClusterIP by default
    selector: # select the Pods the NodePort should expose
        app: posts # all the Pods with this label
    ports:
        - name: posts
          protocol: TCP
          port: 4000 # the port that NodePort listens to
          targetPort: 4000 # the port that the application listens to
