apiVersion: apps/v1
kind: Deployment
metadata:
    name: comments-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: comments
    template:
        metadata:
            name: comments-pod
            labels:
                app: comments
        spec:
            containers:
                - name: comments-containers
                  image: lenhat509/comments:latest
---
apiVersion: v1
kind: Service
metadata:
    name: comments-srv-cip
spec:
    type: ClusterIP # optional
    selector:
        app: comments
    ports:
        - name: comments
          protocol: TCP
          port: 4001
          targetPort: 4001
