apiVersion: apps/v1 # there are certain buckets of different types of objects. Deployment is inside 'apps/v1'
kind: Deployment # type of object
metadata:
    name: posts-depl
spec:
    replicas: 1 # number of Pods that run the image
    selector: # let Deployment know what Pods it should be in charge of in the cluster
        matchLabels:
            app: posts # get all the Pods with this label. 'app' does not have any meaning
    template: # define configuration of the Pods the Depl will create
        metadata:
            name: posts-depl-pod
            labels:
                app: posts # add this label to the Pod so that the Depl can find this Pod
        spec:
            containers:
                - name: posts-depl-container
                  image: lenhat509/posts:latest

---
apiVersion: v1
kind: Service
metadata:
    name: posts-srv-cip
spec:
    type: ClusterIP # optional
    selector:
        app: posts
    ports:
        - name: post
          protocol: TCP
          port: 4000
          targetPort: 4000
