apiVersion: apps/v1
kind: Deployment
metadata:
    name: client-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: client
    template:
        metadata:
            name: client-pod
            labels:
                app: client
        spec:
            containers:
                - name: client-containers
                  image: lenhat509/client:latest
---
apiVersion: v1
kind: Service
metadata:
    name: client-srv-cip
spec:
    type: ClusterIP # optional
    selector:
        app: client
    ports:
        - name: client
          protocol: TCP
          port: 3000
          targetPort: 3000
