apiVersion: apps/v1
kind: Deployment
metadata:
    name: query-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: query
    template:
        metadata:
            name: query-pod
            labels:
                app: query
        spec:
            containers:
                - name: query-containers
                  image: lenhat509/query:latest
---
apiVersion: v1
kind: Service
metadata:
    name: query-srv-cip
spec:
    type: ClusterIP # optional
    selector:
        app: query
    ports:
        - name: query
          protocol: TCP
          port: 4002
          targetPort: 4002
